import { sqliteTable, text, integer, real } from 'drizzle-orm/sqlite-core'

export const SAMData = sqliteTable('SAM_Data', {
  id: text('id').primaryKey(),
  awardIdPiid: text('award_id_piid').notNull().unique(),
  recipientName: text('recipient_name').notNull(),
  obligatedAmount: real('total_obligated_amount').notNull().default(0),
  performanceEnd: text('period_of_performance_current_end_date'),
  naicsDescription: text('naics_description'),
  productCode: text('product_or_service_code_description'),
  agencyName: text('awarding_agency_name'),
  isActive: integer('is_active', { mode: 'boolean' }).notNull().default(true),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
})

export const contractors = sqliteTable('contractors', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  uei: text('uei'),
  duns: text('duns'),
  address: text('address'),
  city: text('city'),
  state: text('state'),
  zipCode: text('zip_code'),
  phone: text('phone'),
  website: text('website'),
  contractingTier: text('contracting_tier').default('Free'),
  notes: text('notes'),
  aviationContractId: text('aviation_contract_id'),
  email1: text('email_1'),
  email2: text('email_2'),
  email3: text('email_3'),
  isActive: integer('is_active', { mode: 'boolean' }).notNull().default(true),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
})

export const contacts = sqliteTable('contacts', {
  id: text('id').primaryKey(),
  contractorId: text('contractor_id').notNull(),
  firstName: text('first_name').notNull(),
  lastName: text('last_name').notNull(),
  title: text('title'),
  email: text('email'),
  phone: text('phone'),
  isPrimary: integer('is_primary', { mode: 'boolean' }).default(false),
  aviationContractId: text('aviation_contract_id'),
  source: text('source'),
  isActive: integer('is_active', { mode: 'boolean' }).notNull().default(true),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
})

export const outreach = sqliteTable('outreach', {
  id: text('id').primaryKey(),
  contractorId: text('contractor_id').notNull(),
  contactId: text('contact_id'),
  aviationContractId: text('aviation_contract_id'),
  status: text('status').notNull().default('Pending'),
  priority: text('priority').notNull().default('Medium'),
  subject: text('subject'),
  notes: text('notes'),
  interactionDate: text('interaction_date'),
  followUpDate: text('follow_up_date'),
  sentDate: text('sent_date'),
  inquiryId: text('inquiry_id'),
  isActive: integer('is_active', { mode: 'boolean' }).notNull().default(true),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
})

export const compliance = sqliteTable('compliance', {
  id: text('id').primaryKey(),
  contractorId: text('contractor_id').notNull(),
  aviationContractId: text('aviation_contract_id'),
  type: text('type').notNull(),
  status: text('status').notNull().default('Pending'),
  requirement: text('requirement').notNull(),
  documentation: text('documentation'),
  expiryDate: text('expiry_date'),
  lastAuditDate: text('last_audit_date'),
  nextAuditDate: text('next_audit_date'),
  riskLevel: text('risk_level').default('Medium'),
  priority: integer('priority').default(0),
  scope: text('scope').default('Contract'),
  notes: text('notes'),
  isActive: integer('is_active', { mode: 'boolean' }).notNull().default(true),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
})

export const inquiries = sqliteTable('inquiries', {
  id: text('id').primaryKey(),
  inquiryId: text('inquiry_id').notNull().unique(),
  partNumber: text('part_number').notNull(),
  partDescription: text('part_description'),
  contractorId: text('contractor_id').notNull(),
  aviationContractId: text('aviation_contract_id'),
  status: text('status').notNull().default('Draft'),
  notes: text('notes'),
  isActive: integer('is_active', { mode: 'boolean' }).notNull().default(true),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
})

export const rfqs = sqliteTable('rfqs', {
  id: text('id').primaryKey(),
  rfqNumber: text('rfq_number').notNull().unique(),
  title: text('title').notNull(),
  partNumber: text('part_number').notNull(),
  partDescription: text('part_description'),
  quantity: integer('quantity').notNull().default(1),
  status: text('status').notNull().default('Draft'),
  aogFlag: integer('aog_flag', { mode: 'boolean' }).default(false),
  contractorId: text('contractor_id'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
})

export const orders = sqliteTable('orders', {
  id: text('id').primaryKey(),
  orderNumber: text('order_number').notNull().unique(),
  rfqId: text('rfq_id').notNull(),
  quoteId: text('quote_id').notNull(),
  contractorId: text('contractor_id').notNull(),
  status: text('status').notNull().default('Pending'),
  totalAmount: real('total_amount').notNull().default(0),
  taxAmount: real('tax_amount').default(0),
  shippingAmount: real('shipping_amount').default(0),
  currency: text('currency').default('USD'),
  paymentStatus: text('payment_status').default('Unpaid'),
  notes: text('notes'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
})

export const companySettings = sqliteTable('company_settings', {
  id: text('id').primaryKey(),
  companyName: text('company_name').default('INTAEROBASE'),
  tagline: text('tagline').default('Aviation Federal Contract Management'),
  address: text('address'),
  city: text('city'),
  state: text('state'),
  zipCode: text('zip_code'),
  country: text('country').default('US'),
  phone: text('phone'),
  phoneAlt: text('phone_alt'),
  email: text('email'),
  website: text('website'),
  logoUrl: text('logo_url'),
  logoSize: integer('logo_size').default(36),
  faviconUrl: text('favicon_url'),
  uei: text('uei'),
  cageCode: text('cage_code'),
  naicsCodes: text('naics_codes'),
  taxId: text('tax_id'),
  duns: text('duns'),
  samRegistration: integer('sam_registration', { mode: 'boolean' }).default(false),
  capabilities: text('capabilities'),
  coreCapabilities: text('core_capabilities'),
  certifications: text('certifications'),
  complianceFrameworks: text('compliance_frameworks'),
  naicsDescriptions: text('naics_descriptions'),
  serviceHighlights: text('service_highlights'),
  whyChooseUs: text('why_choose_us'),
  samGovStatus: text('sam_gov_status'),
  registrationPurpose: text('registration_purpose'),
  ownerName: text('owner_name'),
  defaultCurrency: text('default_currency').default('USD'),
  smtpFromName: text('smtp_from_name'),
  smtpFromEmail: text('smtp_from_email'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
})

export const capabilities = sqliteTable('capabilities', {
  id: text('id').primaryKey(),
  contractorId: text('contractor_id'),
  category: text('category').notNull(),
  name: text('name').notNull(),
  description: text('description'),
  status: text('status').notNull().default('Active'),
  certificationLevel: text('certification_level'),
  expiryDate: text('expiry_date'),
  naicsCode: text('naics_code'),
  aircraftTypes: text('aircraft_types'),
  partNumbers: text('part_numbers'),
  estimatedValue: real('estimated_value').default(0),
  priority: text('priority').default('Medium'),
  notes: text('notes'),
  isActive: integer('is_active', { mode: 'boolean' }).notNull().default(true),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
})

export const notifications = sqliteTable('notifications', {
  id: text('id').primaryKey(),
  userId: text('user_id'),
  type: text('type').notNull(),
  title: text('title').notNull(),
  body: text('body'),
  entityId: text('entity_id'),
  entityType: text('entity_type'),
  isRead: integer('is_read', { mode: 'boolean' }).default(false),
  createdAt: text('created_at').notNull(),
})

export const contracts = sqliteTable('contracts', {
  id: text('id').primaryKey(),
  contractNumber: text('contract_number').notNull().unique(),
  title: text('title').notNull(),
  contractorId: text('contractor_id'),
  contactId: text('contact_id'),
  status: text('status').notNull().default('Draft'),
  totalAmount: real('total_amount').default(0),
  taxAmount: real('tax_amount').default(0),
  shippingAmount: real('shipping_amount').default(0),
  currency: text('currency').default('USD'),
  startDate: text('start_date'),
  endDate: text('end_date'),
  paymentTerms: text('payment_terms'),
  deliveryTerms: text('delivery_terms'),
  notes: text('notes'),
  internalNotes: text('internal_notes'),
  isActive: integer('is_active', { mode: 'boolean' }).notNull().default(true),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
})
